services:
   app:
      image: reversi-dev
      build:
         context: ../
         dockerfile: docker/Dockerfile.dev
      volumes:
         - ../:/usr/src/app
      container_name: reversi-dev
      ports:
         - 3000:3000
      env_file:
         - ../.env
   server:
      image: reversi-dev-server
      build:
         context: ../
         dockerfile: docker/Dockerfile.server.dev
      volumes:
         - ../src:/usr/src/app/src
      container_name: reversi-dev-server
      ports:
         - 3001:3001
      env_file:
         - ../.env
   mongo:
      image: mongo
      ports:
         - 3013:27017
      volumes:
         - ./docker-volume-data/mongodb:/data/mongodb
   nginx:
      image: nginx:latest
      ports:
         - ${ENTRY_PORT:-3005}:80
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
         - app
         - server
      restart: always
      env_file:
         - ../.env
