services:
   app:
      image: reversi
      container_name: reversi
      build:
         context: ../
         dockerfile: docker/Dockerfile.prod
      ports:
         - 3000:3000
      env_file:
         - ../.env
      restart: always
   server:
      image: reversi-server
      container_name: reversi-server
      build:
         context: ../
         dockerfile: docker/Dockerfile.server.prod
      ports:
         - 3001:3001
      env_file:
         - ../.env
      restart: always
   nginx:
      image: nginx:latest
      ports:
         - '${ENTRY_PORT:-3005}:80'
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
         - app
         - server
      restart: always
