services:
   app:
      image: reversi
      container_name: reversi
      build:
         context: ../
         dockerfile: docker/Dockerfile.prod
         args:
            NEXT_PUBLIC_DEDICATED_SOCKET_SERVER: ${STANDALONE_SERVER}
      restart: always
      ports:
         - 3005:3000
      environment:
         - NEXT_PUBLIC_DEDICATED_SOCKET_SERVER=${STANDALONE_SERVER:-""}
      env_file:
         - ../.env
   server:
      image: reversi-server
      container_name: reversi-server
      profiles:
         - standalone
      build:
         context: ../
         dockerfile: docker/Dockerfile.server.prod
      ports:
         - 3001:3001
      environment:
         - NEXT_PUBLIC_DEDICATED_SOCKET_SERVER=${STANDALONE_SERVER:-""}
      env_file:
         - ../.env
