import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';

const roboto = Roboto({
   variable: '--font-roboto',
   subsets: ['latin'],
});

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={` ${roboto.className} antialiased w-screen h-screen flex flex-col`}
         >
            <div className="bg-gray-800 border-b-3 border-teal-500 p-4">
               <h1 className="font-black text-2xl text-gray-100">
                  CHRISTOPHER KOLB
               </h1>
               <h2 className="font-black text-xl pl-8 pt-2 text-gray-100">
                  Reversi
               </h2>
            </div>
            {children}
         </body>
      </html>
   );
}
